spring:
  application:
    name: zuul
server:
  port: 5001
logging:
  level:
    root: INFO
eureka:
  client: 
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    point: /p/**
    member: /m/**
management:
  security:
    enabled: false
