security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin123
server:
  port: 8761
logging:
  level:
    root: ERROR
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://admin:admin123@localhost:8761/eureka