server:
  port: 9999
logging:
  level:
    root: INFO
spring:
  application:
    name: config-server
  cloud:
    config:
     server:
        git:
          uri: https://github.com/ahitbo/repo-spring-cloud
