server:
  port: 9979
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin123
logging:
  level:
    root: INFO
spring:
  application:
    name: config-server
  cloud:
    config:
     server:
        git:
          uri: https://github.com/ahitbo/repo-spring-cloud.git
          username: aihao001
          password: ah11271126
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    metadataMap:
      user: admin
      password: admin123
encrypt:
  key: wufang
