spring:
  application:
    name: member-admin
server:
  port: 8081
management:
  port: 6081
logging:
  level:
    root: ERROR
eureka:
  client: 
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      management.port: 6081
member: 
  ribbon: 
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
feign: 
  hystrix: 
    enabled: true