spring:
  application:
    name: hystrix-turbine
server:
  port: 9002
logging:
  level:
    root: ERROR
eureka:
  client: 
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: default
  appConfig: member-admin,point-admin
  clusterNameExpression: "'default'"